export enum TraceFlag {
  NONE,
  INTERSECT_WORLD,
  INTERSECT_VEHICLES,
  INTERSECT_PEDS_SIMPLE_COLLISION = 4,
  INTERSECT_PEDS = 8,
  INTERSECT_OBJECTS = 16,
  INTERSECT_WATER = 32,
  UNKNOWN = 128,
  INTERSECT_FOLIAGE = 256,
  INTERSECT_EVERYTHING = 4294967295,
}
