"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VehicleSeat = void 0;
var VehicleSeat;
(function (VehicleSeat) {
    VehicleSeat[VehicleSeat["None"] = -3] = "None";
    VehicleSeat[VehicleSeat["Any"] = -2] = "Any";
    VehicleSeat[VehicleSeat["Driver"] = -1] = "Driver";
    VehicleSeat[VehicleSeat["Passenger"] = 0] = "Passenger";
    VehicleSeat[VehicleSeat["LeftFront"] = -1] = "LeftFront";
    VehicleSeat[VehicleSeat["RightFront"] = 0] = "RightFront";
    VehicleSeat[VehicleSeat["LeftRear"] = 1] = "LeftRear";
    VehicleSeat[VehicleSeat["RightRear"] = 2] = "RightRear";
    VehicleSeat[VehicleSeat["ExtraSeat1"] = 3] = "ExtraSeat1";
    VehicleSeat[VehicleSeat["ExtraSeat2"] = 4] = "ExtraSeat2";
    VehicleSeat[VehicleSeat["ExtraSeat3"] = 5] = "ExtraSeat3";
    VehicleSeat[VehicleSeat["ExtraSeat4"] = 6] = "ExtraSeat4";
    VehicleSeat[VehicleSeat["ExtraSeat5"] = 7] = "ExtraSeat5";
    VehicleSeat[VehicleSeat["ExtraSeat6"] = 8] = "ExtraSeat6";
    VehicleSeat[VehicleSeat["ExtraSeat7"] = 9] = "ExtraSeat7";
    VehicleSeat[VehicleSeat["ExtraSeat8"] = 10] = "ExtraSeat8";
    VehicleSeat[VehicleSeat["ExtraSeat9"] = 11] = "ExtraSeat9";
    VehicleSeat[VehicleSeat["ExtraSeat10"] = 12] = "ExtraSeat10";
    VehicleSeat[VehicleSeat["ExtraSeat11"] = 13] = "ExtraSeat11";
    VehicleSeat[VehicleSeat["ExtraSeat12"] = 14] = "ExtraSeat12";
})(VehicleSeat || (exports.VehicleSeat = VehicleSeat = {}));
