"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VehicleClass = void 0;
var VehicleClass;
(function (VehicleClass) {
    VehicleClass[VehicleClass["Compacts"] = 0] = "Compacts";
    VehicleClass[VehicleClass["Sedans"] = 1] = "Sedans";
    VehicleClass[VehicleClass["SUVs"] = 2] = "SUVs";
    VehicleClass[VehicleClass["Coupes"] = 3] = "Coupes";
    VehicleClass[VehicleClass["Muscle"] = 4] = "Muscle";
    VehicleClass[VehicleClass["SportsClassics"] = 5] = "SportsClassics";
    VehicleClass[VehicleClass["Sports"] = 6] = "Sports";
    VehicleClass[VehicleClass["Super"] = 7] = "Super";
    VehicleClass[VehicleClass["Motorcycles"] = 8] = "Motorcycles";
    VehicleClass[VehicleClass["OffRoad"] = 9] = "OffRoad";
    VehicleClass[VehicleClass["Industrial"] = 10] = "Industrial";
    VehicleClass[VehicleClass["Utility"] = 11] = "Utility";
    VehicleClass[VehicleClass["Vans"] = 12] = "Vans";
    VehicleClass[VehicleClass["Cycles"] = 13] = "Cycles";
    VehicleClass[VehicleClass["Boats"] = 14] = "Boats";
    VehicleClass[VehicleClass["Helicopters"] = 15] = "Helicopters";
    VehicleClass[VehicleClass["Planes"] = 16] = "Planes";
    VehicleClass[VehicleClass["Service"] = 17] = "Service";
    VehicleClass[VehicleClass["Emergency"] = 18] = "Emergency";
    VehicleClass[VehicleClass["Military"] = 19] = "Military";
    VehicleClass[VehicleClass["Commercial"] = 20] = "Commercial";
    VehicleClass[VehicleClass["Trains"] = 21] = "Trains";
})(VehicleClass || (exports.VehicleClass = VehicleClass = {}));
