export enum PopulationType {
    UNKNOWN,
    RANDOM_PERMANENT,
    RANDOM_PARKED,
    RANDOM_PATROL,
    RANDOM_SCENARIO,
    RANDOM_AMBIENT,
    PERMANENT,
    MISSION,
    REPLAY,
    CACHE,
    TOOL,
}